on:
  push:
  pull_request:

name: CI
jobs:

  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install and build
        run: |
          npm ci
          npm run minify
      - name: Upload website to Grebedoc
        run: |
          set -o pipefail
          tar -C dist -c . | zstd -T0 -1 | curl https://webusb.glasgow-embedded.org/ -X PUT -H "Authorization: Pages ${{ secrets.GREBEDOC_TOKEN }}" -H "Content-Type: application/x-tar+zstd" -T -
